---
- name: Install Dify.AI locally
  hosts: local
  become: true
  vars:
    dify_install_dir: ~/dify

  tasks:
    - name: Install prerequisites
      package:
        name: ['git', 'curl', 'apt-transport-https', 'ca-certificates', 'software-properties-common']
        state: present

    - name: Install Docker using official convenience script
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Install Docker Compose (plugin version)
      shell: |
        mkdir -p ~/.docker/cli-plugins/
        curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose
      args:
        creates: ~/.docker/cli-plugins/docker-compose

    - name: Clone Dify repository
      git:
        repo: https://github.com/langgenius/dify.git
        dest: "{{ dify_install_dir }}"
        version: main

    - name: Copy example .env
      copy:
        src: "{{ dify_install_dir }}/docker/.env.example"
        dest: "{{ dify_install_dir }}/docker/.env"
        remote_src: yes
      notify: Restart Dify stack

    - name: Start Dify with Docker Compose
      shell: docker compose up -d
      args:
        chdir: "{{ dify_install_dir }}/docker"
      notify: Restart Dify stack

  handlers:
    - name: Restart Dify stack
      shell: docker compose down && docker compose up -d
      args:
        chdir: "{{ dify_install_dir }}/docker"
